/*
 * LocalServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


 package io.swagger.client.model;

 import java.util.Objects;
 import com.google.gson.annotations.SerializedName;
 import io.swagger.annotations.ApiModel;
 import io.swagger.annotations.ApiModelProperty;
 
 /**
  * 
  */
 @ApiModel(description = "")
 @javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-03-05T11:32:31.617-05:00")
 public class BurpIssueCollaboratorEvent {
   @SerializedName("InteractionType")
   private String interactionType = null;
 
   @SerializedName("OriginIp")
   private String originIp = null;
 
   @SerializedName("Time")
   private String time = null;
 
   @SerializedName("LookupType")
   private String lookupType = null;
 
   @SerializedName("LookupHost")
   private String lookupHost = null;
 
   @SerializedName("RequestResponse")
   private BurpIssueRequestResponse requestResponse = null;
 
   @SerializedName("SMTP")
   private BurpIssueSMTP SMTP = null;
 
   public BurpIssueCollaboratorEvent interactionType(String interactionType) {
     this.interactionType = interactionType;
     return this;
   }
 
    /**
    * Get interactionType
    * @return interactionType
   **/
   @ApiModelProperty(value = "")
   public String getInteractionType() {
     return interactionType;
   }
 
   public void setInteractionType(String interactionType) {
     this.interactionType = interactionType;
   }
 
   public BurpIssueCollaboratorEvent originIp(String originIp) {
     this.originIp = originIp;
     return this;
   }
 
    /**
    * Get originIp
    * @return originIp
   **/
   @ApiModelProperty(value = "")
   public String getOriginIp() {
     return originIp;
   }
 
   public void setOriginIp(String originIp) {
     this.originIp = originIp;
   }
 
   public BurpIssueCollaboratorEvent time(String time) {
     this.time = time;
     return this;
   }
 
    /**
    * Get time
    * @return time
   **/
   @ApiModelProperty(value = "")
   public String getTime() {
     return time;
   }
 
   public void setTime(String time) {
     this.time = time;
   }
 
   public BurpIssueCollaboratorEvent lookupType(String lookupType) {
     this.lookupType = lookupType;
     return this;
   }
 
    /**
    * Get lookupType
    * @return lookupType
   **/
   @ApiModelProperty(value = "")
   public String getLookupType() {
     return lookupType;
   }
 
   public void setLookupType(String lookupType) {
     this.lookupType = lookupType;
   }
 
   public BurpIssueCollaboratorEvent lookupHost(String lookupHost) {
     this.lookupHost = lookupHost;
     return this;
   }
 
    /**
    * Get lookupHost
    * @return lookupHost
   **/
   @ApiModelProperty(value = "")
   public String getLookupHost() {
     return lookupHost;
   }
 
   public void setLookupHost(String lookupHost) {
     this.lookupHost = lookupHost;
   }
 
   public BurpIssueCollaboratorEvent requestResponse(BurpIssueRequestResponse requestResponse) {
     this.requestResponse = requestResponse;
     return this;
   }
 
    /**
    * Get requestResponse
    * @return requestResponse
   **/
   @ApiModelProperty(value = "")
   public BurpIssueRequestResponse getRequestResponse() {
     return requestResponse;
   }
 
   public void setRequestResponse(BurpIssueRequestResponse requestResponse) {
     this.requestResponse = requestResponse;
   }
 
   public BurpIssueCollaboratorEvent SMTP(BurpIssueSMTP SMTP) {
     this.SMTP = SMTP;
     return this;
   }
 
    /**
    * Get SMTP
    * @return SMTP
   **/
   @ApiModelProperty(value = "")
   public BurpIssueSMTP getSMTP() {
     return SMTP;
   }
 
   public void setSMTP(BurpIssueSMTP SMTP) {
     this.SMTP = SMTP;
   }
 
 
   @Override
   public boolean equals(java.lang.Object o) {
     if (this == o) {
       return true;
     }
     if (o == null || getClass() != o.getClass()) {
       return false;
     }
     BurpIssueCollaboratorEvent burpIssueCollaboratorEvent = (BurpIssueCollaboratorEvent) o;
     return Objects.equals(this.interactionType, burpIssueCollaboratorEvent.interactionType) &&
         Objects.equals(this.originIp, burpIssueCollaboratorEvent.originIp) &&
         Objects.equals(this.time, burpIssueCollaboratorEvent.time) &&
         Objects.equals(this.lookupType, burpIssueCollaboratorEvent.lookupType) &&
         Objects.equals(this.lookupHost, burpIssueCollaboratorEvent.lookupHost) &&
         Objects.equals(this.requestResponse, burpIssueCollaboratorEvent.requestResponse) &&
         Objects.equals(this.SMTP, burpIssueCollaboratorEvent.SMTP);
   }
 
   @Override
   public int hashCode() {
     return Objects.hash(interactionType, originIp, time, lookupType, lookupHost, requestResponse, SMTP);
   }
 
 
   @Override
   public String toString() {
     StringBuilder sb = new StringBuilder();
     sb.append("class BurpIssueCollaboratorEvent {\n");
     
     sb.append("    interactionType: ").append(toIndentedString(interactionType)).append("\n");
     sb.append("    originIp: ").append(toIndentedString(originIp)).append("\n");
     sb.append("    time: ").append(toIndentedString(time)).append("\n");
     sb.append("    lookupType: ").append(toIndentedString(lookupType)).append("\n");
     sb.append("    lookupHost: ").append(toIndentedString(lookupHost)).append("\n");
     sb.append("    requestResponse: ").append(toIndentedString(requestResponse)).append("\n");
     sb.append("    SMTP: ").append(toIndentedString(SMTP)).append("\n");
     sb.append("}");
     return sb.toString();
   }
 
   /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
   private String toIndentedString(java.lang.Object o) {
     if (o == null) {
       return "null";
     }
     return o.toString().replace("\n", "\n    ");
   }
 
 }
 
 