/*
 * LocalServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


 package io.swagger.client.model;

 import java.util.Objects;
 import com.google.gson.annotations.SerializedName;
 import io.swagger.annotations.ApiModel;
 import io.swagger.annotations.ApiModelProperty;
 import java.util.ArrayList;
 import java.util.List;
 
 /**
  * 
  */
 @ApiModel(description = "")
 @javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-03-05T11:32:31.617-05:00")
 public class BurpIssueStaticAnalysisItem {
   @SerializedName("Source")
   private String source = null;
 
   @SerializedName("Sink")
   private String sink = null;
 
   @SerializedName("CodeSnippets")
   private List<String> codeSnippets = null;
 
   public BurpIssueStaticAnalysisItem source(String source) {
     this.source = source;
     return this;
   }
 
    /**
    * Get source
    * @return source
   **/
   @ApiModelProperty(value = "")
   public String getSource() {
     return source;
   }
 
   public void setSource(String source) {
     this.source = source;
   }
 
   public BurpIssueStaticAnalysisItem sink(String sink) {
     this.sink = sink;
     return this;
   }
 
    /**
    * Get sink
    * @return sink
   **/
   @ApiModelProperty(value = "")
   public String getSink() {
     return sink;
   }
 
   public void setSink(String sink) {
     this.sink = sink;
   }
 
   public BurpIssueStaticAnalysisItem codeSnippets(List<String> codeSnippets) {
     this.codeSnippets = codeSnippets;
     return this;
   }
 
   public BurpIssueStaticAnalysisItem addCodeSnippetsItem(String codeSnippetsItem) {
     if (this.codeSnippets == null) {
       this.codeSnippets = new ArrayList<String>();
     }
     this.codeSnippets.add(codeSnippetsItem);
     return this;
   }
 
    /**
    * Get codeSnippets
    * @return codeSnippets
   **/
   @ApiModelProperty(value = "")
   public List<String> getCodeSnippets() {
     return codeSnippets;
   }
 
   public void setCodeSnippets(List<String> codeSnippets) {
     this.codeSnippets = codeSnippets;
   }
 
 
   @Override
   public boolean equals(java.lang.Object o) {
     if (this == o) {
       return true;
     }
     if (o == null || getClass() != o.getClass()) {
       return false;
     }
     BurpIssueStaticAnalysisItem burpIssueStaticAnalysisItem = (BurpIssueStaticAnalysisItem) o;
     return Objects.equals(this.source, burpIssueStaticAnalysisItem.source) &&
         Objects.equals(this.sink, burpIssueStaticAnalysisItem.sink) &&
         Objects.equals(this.codeSnippets, burpIssueStaticAnalysisItem.codeSnippets);
   }
 
   @Override
   public int hashCode() {
     return Objects.hash(source, sink, codeSnippets);
   }
 
 
   @Override
   public String toString() {
     StringBuilder sb = new StringBuilder();
     sb.append("class BurpIssueStaticAnalysisItem {\n");
     
     sb.append("    source: ").append(toIndentedString(source)).append("\n");
     sb.append("    sink: ").append(toIndentedString(sink)).append("\n");
     sb.append("    codeSnippets: ").append(toIndentedString(codeSnippets)).append("\n");
     sb.append("}");
     return sb.toString();
   }
 
   /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
   private String toIndentedString(java.lang.Object o) {
     if (o == null) {
       return "null";
     }
     return o.toString().replace("\n", "\n    ");
   }
 
 }
 
 