/*
 * LocalServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


 package io.swagger.client.model;

 import java.util.Objects;
 import com.google.gson.TypeAdapter;
 import com.google.gson.annotations.JsonAdapter;
 import com.google.gson.annotations.SerializedName;
 import com.google.gson.stream.JsonReader;
 import com.google.gson.stream.JsonWriter;
 import io.swagger.annotations.ApiModel;
 import io.swagger.annotations.ApiModelProperty;
 import java.io.IOException;
 
 /**
  * 
  */
 @ApiModel(description = "")
 @javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-03-05T11:32:31.617-05:00")
 public class BurpIssueHost {
   @SerializedName("Value")
   private String value = null;
 
   @SerializedName("IpAddress")
   private String ipAddress = null;
 
   public BurpIssueHost value(String value) {
     this.value = value;
     return this;
   }
 
    /**
    * Get value
    * @return value
   **/
   @ApiModelProperty(value = "")
   public String getValue() {
     return value;
   }
 
   public void setValue(String value) {
     this.value = value;
   }
 
   public BurpIssueHost ipAddress(String ipAddress) {
     this.ipAddress = ipAddress;
     return this;
   }
 
    /**
    * Get ipAddress
    * @return ipAddress
   **/
   @ApiModelProperty(value = "")
   public String getIpAddress() {
     return ipAddress;
   }
 
   public void setIpAddress(String ipAddress) {
     this.ipAddress = ipAddress;
   }
 
 
   @Override
   public boolean equals(java.lang.Object o) {
     if (this == o) {
       return true;
     }
     if (o == null || getClass() != o.getClass()) {
       return false;
     }
     BurpIssueHost burpIssueHost = (BurpIssueHost) o;
     return Objects.equals(this.value, burpIssueHost.value) &&
         Objects.equals(this.ipAddress, burpIssueHost.ipAddress);
   }
 
   @Override
   public int hashCode() {
     return Objects.hash(value, ipAddress);
   }
 
 
   @Override
   public String toString() {
     StringBuilder sb = new StringBuilder();
     sb.append("class BurpIssueHost {\n");
     
     sb.append("    value: ").append(toIndentedString(value)).append("\n");
     sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
     sb.append("}");
     return sb.toString();
   }
 
   /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
   private String toIndentedString(java.lang.Object o) {
     if (o == null) {
       return "null";
     }
     return o.toString().replace("\n", "\n    ");
   }
 
 }
 
 