/*
 * LocalServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


 package io.swagger.client.model;

 import java.util.Objects;
 import com.google.gson.annotations.SerializedName;
 import io.swagger.annotations.ApiModel;
 import io.swagger.annotations.ApiModelProperty;
 
 /**
  * 
  */
 @ApiModel(description = "")
 @javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-03-05T11:32:31.617-05:00")
 public class BurpIssueRequest {
   @SerializedName("Text")
   private String text = null;
 
   @SerializedName("IsBase64")
   private Boolean isBase64 = null;
 
   @SerializedName("Method")
   private String method = null;
 
   public BurpIssueRequest text(String text) {
     this.text = text;
     return this;
   }
 
    /**
    * Get text
    * @return text
   **/
   @ApiModelProperty(value = "")
   public String getText() {
     return text;
   }
 
   public void setText(String text) {
     this.text = text;
   }
 
   public BurpIssueRequest isBase64(Boolean isBase64) {
     this.isBase64 = isBase64;
     return this;
   }
 
    /**
    * Get isBase64
    * @return isBase64
   **/
   @ApiModelProperty(value = "")
   public Boolean isIsBase64() {
     return isBase64;
   }
 
   public void setIsBase64(Boolean isBase64) {
     this.isBase64 = isBase64;
   }
 
   public BurpIssueRequest method(String method) {
     this.method = method;
     return this;
   }
 
    /**
    * Get method
    * @return method
   **/
   @ApiModelProperty(value = "")
   public String getMethod() {
     return method;
   }
 
   public void setMethod(String method) {
     this.method = method;
   }
 
 
   @Override
   public boolean equals(java.lang.Object o) {
     if (this == o) {
       return true;
     }
     if (o == null || getClass() != o.getClass()) {
       return false;
     }
     BurpIssueRequest burpIssueRequest = (BurpIssueRequest) o;
     return Objects.equals(this.text, burpIssueRequest.text) &&
         Objects.equals(this.isBase64, burpIssueRequest.isBase64) &&
         Objects.equals(this.method, burpIssueRequest.method);
   }
 
   @Override
   public int hashCode() {
     return Objects.hash(text, isBase64, method);
   }
 
 
   @Override
   public String toString() {
     StringBuilder sb = new StringBuilder();
     sb.append("class BurpIssueRequest {\n");
     
     sb.append("    text: ").append(toIndentedString(text)).append("\n");
     sb.append("    isBase64: ").append(toIndentedString(isBase64)).append("\n");
     sb.append("    method: ").append(toIndentedString(method)).append("\n");
     sb.append("}");
     return sb.toString();
   }
 
   /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
   private String toIndentedString(java.lang.Object o) {
     if (o == null) {
       return "null";
     }
     return o.toString().replace("\n", "\n    ");
   }
 
 }
 
 