/*
 * LocalServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


 package io.swagger.client.model;

 import java.util.Objects;
 import com.google.gson.TypeAdapter;
 import com.google.gson.annotations.JsonAdapter;
 import com.google.gson.annotations.SerializedName;
 import com.google.gson.stream.JsonReader;
 import com.google.gson.stream.JsonWriter;
 import io.swagger.annotations.ApiModel;
 import io.swagger.annotations.ApiModelProperty;
 import java.io.IOException;
 import java.util.ArrayList;
 import java.util.List;
 
 /**
  * 
  */
 @ApiModel(description = "")
 @javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-03-05T11:32:31.617-05:00")
 public class BurpIssueSMTP {
   @SerializedName("Sender")
   private String sender = null;
 
   @SerializedName("Message")
   private String message = null;
 
   @SerializedName("Conversation")
   private String conversation = null;
 
   @SerializedName("Recipients")
   private List<String> recipients = null;
 
   public BurpIssueSMTP sender(String sender) {
     this.sender = sender;
     return this;
   }
 
    /**
    * Get sender
    * @return sender
   **/
   @ApiModelProperty(value = "")
   public String getSender() {
     return sender;
   }
 
   public void setSender(String sender) {
     this.sender = sender;
   }
 
   public BurpIssueSMTP message(String message) {
     this.message = message;
     return this;
   }
 
    /**
    * Get message
    * @return message
   **/
   @ApiModelProperty(value = "")
   public String getMessage() {
     return message;
   }
 
   public void setMessage(String message) {
     this.message = message;
   }
 
   public BurpIssueSMTP conversation(String conversation) {
     this.conversation = conversation;
     return this;
   }
 
    /**
    * Get conversation
    * @return conversation
   **/
   @ApiModelProperty(value = "")
   public String getConversation() {
     return conversation;
   }
 
   public void setConversation(String conversation) {
     this.conversation = conversation;
   }
 
   public BurpIssueSMTP recipients(List<String> recipients) {
     this.recipients = recipients;
     return this;
   }
 
   public BurpIssueSMTP addRecipientsItem(String recipientsItem) {
     if (this.recipients == null) {
       this.recipients = new ArrayList<String>();
     }
     this.recipients.add(recipientsItem);
     return this;
   }
 
    /**
    * Get recipients
    * @return recipients
   **/
   @ApiModelProperty(value = "")
   public List<String> getRecipients() {
     return recipients;
   }
 
   public void setRecipients(List<String> recipients) {
     this.recipients = recipients;
   }
 
 
   @Override
   public boolean equals(java.lang.Object o) {
     if (this == o) {
       return true;
     }
     if (o == null || getClass() != o.getClass()) {
       return false;
     }
     BurpIssueSMTP burpIssueSMTP = (BurpIssueSMTP) o;
     return Objects.equals(this.sender, burpIssueSMTP.sender) &&
         Objects.equals(this.message, burpIssueSMTP.message) &&
         Objects.equals(this.conversation, burpIssueSMTP.conversation) &&
         Objects.equals(this.recipients, burpIssueSMTP.recipients);
   }
 
   @Override
   public int hashCode() {
     return Objects.hash(sender, message, conversation, recipients);
   }
 
 
   @Override
   public String toString() {
     StringBuilder sb = new StringBuilder();
     sb.append("class BurpIssueSMTP {\n");
     
     sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
     sb.append("    message: ").append(toIndentedString(message)).append("\n");
     sb.append("    conversation: ").append(toIndentedString(conversation)).append("\n");
     sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
     sb.append("}");
     return sb.toString();
   }
 
   /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
   private String toIndentedString(java.lang.Object o) {
     if (o == null) {
       return "null";
     }
     return o.toString().replace("\n", "\n    ");
   }
 
 }
 
 