/*
 * LocalServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BurpHttpService;
import io.swagger.client.model.BurpTraffic;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BurpIssue
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-20T09:30:08.127-04:00")
public class BurpIssue {
  @SerializedName("Name")
  private String name = null;

  @SerializedName("Url")
  private String url = null;

  @SerializedName("Severity")
  private String severity = null;

  @SerializedName("Confidence")
  private String confidence = null;

  @SerializedName("HttpService")
  private BurpHttpService httpService = null;

  @SerializedName("Traffic")
  private List<BurpTraffic> traffic = null;

  @SerializedName("Description")
  private String description = null;

  public BurpIssue name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BurpIssue url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @ApiModelProperty(value = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public BurpIssue severity(String severity) {
    this.severity = severity;
    return this;
  }

   /**
   * Get severity
   * @return severity
  **/
  @ApiModelProperty(value = "")
  public String getSeverity() {
    return severity;
  }

  public void setSeverity(String severity) {
    this.severity = severity;
  }

  public BurpIssue confidence(String confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Get confidence
   * @return confidence
  **/
  @ApiModelProperty(value = "")
  public String getConfidence() {
    return confidence;
  }

  public void setConfidence(String confidence) {
    this.confidence = confidence;
  }

  public BurpIssue httpService(BurpHttpService httpService) {
    this.httpService = httpService;
    return this;
  }

   /**
   * Get httpService
   * @return httpService
  **/
  @ApiModelProperty(value = "")
  public BurpHttpService getHttpService() {
    return httpService;
  }

  public void setHttpService(BurpHttpService httpService) {
    this.httpService = httpService;
  }

  public BurpIssue traffic(List<BurpTraffic> traffic) {
    this.traffic = traffic;
    return this;
  }

  public BurpIssue addTrafficItem(BurpTraffic trafficItem) {
    if (this.traffic == null) {
      this.traffic = new ArrayList<BurpTraffic>();
    }
    this.traffic.add(trafficItem);
    return this;
  }

   /**
   * Get traffic
   * @return traffic
  **/
  @ApiModelProperty(value = "")
  public List<BurpTraffic> getTraffic() {
    return traffic;
  }

  public void setTraffic(List<BurpTraffic> traffic) {
    this.traffic = traffic;
  }

  public BurpIssue description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BurpIssue burpIssue = (BurpIssue) o;
    return Objects.equals(this.name, burpIssue.name) &&
        Objects.equals(this.url, burpIssue.url) &&
        Objects.equals(this.severity, burpIssue.severity) &&
        Objects.equals(this.confidence, burpIssue.confidence) &&
        Objects.equals(this.httpService, burpIssue.httpService) &&
        Objects.equals(this.traffic, burpIssue.traffic) &&
        Objects.equals(this.description, burpIssue.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, url, severity, confidence, httpService, traffic, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BurpIssue {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    severity: ").append(toIndentedString(severity)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    httpService: ").append(toIndentedString(httpService)).append("\n");
    sb.append("    traffic: ").append(toIndentedString(traffic)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

