/*
 * LocalServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BurpMenu;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * BurpMenu
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-20T09:30:08.127-04:00")
public class BurpMenu {
  @SerializedName("Name")
  private String name = null;

  /**
   * Gets or Sets type
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    NUMBER_0(0),
    
    NUMBER_1(1),
    
    NUMBER_2(2),
    
    NUMBER_3(3),
    
    NUMBER_4(4);

    private Integer value;

    TypeEnum(Integer value) {
      this.value = value;
    }

    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String text) {
      for (TypeEnum b : TypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        Integer value = jsonReader.nextInt();
        return TypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("Type")
  private TypeEnum type = null;

  @SerializedName("ScanID")
  private UUID scanID = null;

  @SerializedName("SubMenus")
  private List<BurpMenu> subMenus = null;

  @SerializedName("ApplicationName")
  private String applicationName = null;

  public BurpMenu name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BurpMenu type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public BurpMenu scanID(UUID scanID) {
    this.scanID = scanID;
    return this;
  }

   /**
   * Get scanID
   * @return scanID
  **/
  @ApiModelProperty(value = "")
  public UUID getScanID() {
    return scanID;
  }

  public void setScanID(UUID scanID) {
    this.scanID = scanID;
  }

  public BurpMenu subMenus(List<BurpMenu> subMenus) {
    this.subMenus = subMenus;
    return this;
  }

  public BurpMenu addSubMenusItem(BurpMenu subMenusItem) {
    if (this.subMenus == null) {
      this.subMenus = new ArrayList<BurpMenu>();
    }
    this.subMenus.add(subMenusItem);
    return this;
  }

   /**
   * Get subMenus
   * @return subMenus
  **/
  @ApiModelProperty(value = "")
  public List<BurpMenu> getSubMenus() {
    return subMenus;
  }

  public void setSubMenus(List<BurpMenu> subMenus) {
    this.subMenus = subMenus;
  }

  public BurpMenu applicationName(String applicationName) {
    this.applicationName = applicationName;
    return this;
  }

   /**
   * Get applicationName
   * @return applicationName
  **/
  @ApiModelProperty(value = "")
  public String getApplicationName() {
    return applicationName;
  }

  public void setApplicationName(String applicationName) {
    this.applicationName = applicationName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BurpMenu burpMenu = (BurpMenu) o;
    return Objects.equals(this.name, burpMenu.name) &&
        Objects.equals(this.type, burpMenu.type) &&
        Objects.equals(this.scanID, burpMenu.scanID) &&
        Objects.equals(this.subMenus, burpMenu.subMenus) &&
        Objects.equals(this.applicationName, burpMenu.applicationName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, scanID, subMenus, applicationName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BurpMenu {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    scanID: ").append(toIndentedString(scanID)).append("\n");
    sb.append("    subMenus: ").append(toIndentedString(subMenus)).append("\n");
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

