/*
 * LocalServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 0 &#x3D; Parent () 1 &#x3D; RunScan () 2 &#x3D; GetSiteMap () 3 &#x3D;
 * GetIssues () 4 &#x3D; GetScan () 5 &#x3D; SendToVenari () 6 &#x3D;
 * SendIssuesToVenari ()
 */
@JsonAdapter(BurpMenuType.Adapter.class)
public enum BurpMenuType {

  NUMBER_0(0),

  NUMBER_1(1),

  NUMBER_2(2),

  NUMBER_3(3),

  NUMBER_4(4),

  NUMBER_5(5),

  NUMBER_6(6);

  private Integer value;

  BurpMenuType(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BurpMenuType fromValue(String text) {
    for (BurpMenuType b : BurpMenuType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<BurpMenuType> {
    @Override
    public void write(final JsonWriter jsonWriter, final BurpMenuType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BurpMenuType read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return BurpMenuType.fromValue(String.valueOf(value));
    }
  }
}
