/*
 * LocalServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * BurpNotifications
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-10-20T09:30:08.127-04:00")
public class BurpNotifications {
  @SerializedName("Changes")
  private List<BurpNotification> changes = null;

  @SerializedName("IsComplete")
  private Boolean isComplete = null;

  public BurpNotifications changes(List<BurpNotification> changes) {
    this.changes = changes;
    return this;
  }

  public BurpNotifications addChangesItem(BurpNotification changesItem) {
    if (this.changes == null) {
      this.changes = new ArrayList<BurpNotification>();
    }
    this.changes.add(changesItem);
    return this;
  }

   /**
   * Get changes
   * @return changes
  **/
  @ApiModelProperty(value = "")
  public List<BurpNotification> getChanges() {
    return changes;
  }

  public void setChanges(List<BurpNotification> changes) {
    this.changes = changes;
  }

  public BurpNotifications isComplete(Boolean isComplete) {
    this.isComplete = isComplete;
    return this;
  }

   /**
   * Get isComplete
   * @return isComplete
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsComplete() {
    return isComplete;
  }

  public void setIsComplete(Boolean isComplete) {
    this.isComplete = isComplete;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BurpNotifications burpNotifications = (BurpNotifications) o;
    return Objects.equals(this.changes, burpNotifications.changes) &&
        Objects.equals(this.isComplete, burpNotifications.isComplete);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changes, isComplete);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BurpNotifications {\n");
    
    sb.append("    changes: ").append(toIndentedString(changes)).append("\n");
    sb.append("    isComplete: ").append(toIndentedString(isComplete)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

