/*
 * LocalServer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


 package io.swagger.client.model;

 import java.util.Objects;
 import com.google.gson.annotations.SerializedName;
 import io.swagger.annotations.ApiModel;
 import io.swagger.annotations.ApiModelProperty;
 
 /**
  * 
  */
 @ApiModel(description = "")
 @javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-03-05T11:32:31.617-05:00")
 public class BurpIssuePrototypePollutionItem {
   @SerializedName("POC")
   private String POC = null;
 
   @SerializedName("PollutionTechnique")
   private String pollutionTechnique = null;
 
   @SerializedName("PollutionType")
   private String pollutionType = null;
 
   public BurpIssuePrototypePollutionItem POC(String POC) {
     this.POC = POC;
     return this;
   }
 
    /**
    * Get POC
    * @return POC
   **/
   @ApiModelProperty(value = "")
   public String getPOC() {
     return POC;
   }
 
   public void setPOC(String POC) {
     this.POC = POC;
   }
 
   public BurpIssuePrototypePollutionItem pollutionTechnique(String pollutionTechnique) {
     this.pollutionTechnique = pollutionTechnique;
     return this;
   }
 
    /**
    * Get pollutionTechnique
    * @return pollutionTechnique
   **/
   @ApiModelProperty(value = "")
   public String getPollutionTechnique() {
     return pollutionTechnique;
   }
 
   public void setPollutionTechnique(String pollutionTechnique) {
     this.pollutionTechnique = pollutionTechnique;
   }
 
   public BurpIssuePrototypePollutionItem pollutionType(String pollutionType) {
     this.pollutionType = pollutionType;
     return this;
   }
 
    /**
    * Get pollutionType
    * @return pollutionType
   **/
   @ApiModelProperty(value = "")
   public String getPollutionType() {
     return pollutionType;
   }
 
   public void setPollutionType(String pollutionType) {
     this.pollutionType = pollutionType;
   }
 
 
   @Override
   public boolean equals(java.lang.Object o) {
     if (this == o) {
       return true;
     }
     if (o == null || getClass() != o.getClass()) {
       return false;
     }
     BurpIssuePrototypePollutionItem burpIssuePrototypePollutionItem = (BurpIssuePrototypePollutionItem) o;
     return Objects.equals(this.POC, burpIssuePrototypePollutionItem.POC) &&
         Objects.equals(this.pollutionTechnique, burpIssuePrototypePollutionItem.pollutionTechnique) &&
         Objects.equals(this.pollutionType, burpIssuePrototypePollutionItem.pollutionType);
   }
 
   @Override
   public int hashCode() {
     return Objects.hash(POC, pollutionTechnique, pollutionType);
   }
 
 
   @Override
   public String toString() {
     StringBuilder sb = new StringBuilder();
     sb.append("class BurpIssuePrototypePollutionItem {\n");
     
     sb.append("    POC: ").append(toIndentedString(POC)).append("\n");
     sb.append("    pollutionTechnique: ").append(toIndentedString(pollutionTechnique)).append("\n");
     sb.append("    pollutionType: ").append(toIndentedString(pollutionType)).append("\n");
     sb.append("}");
     return sb.toString();
   }
 
   /**
    * Convert the given object to string with each line indented by 4 spaces
    * (except the first line).
    */
   private String toIndentedString(java.lang.Object o) {
     if (o == null) {
       return "null";
     }
     return o.toString().replace("\n", "\n    ");
   }
 
 }
 
 